data_dir: data
images_path: data/images.npy
labels_path: data/labels.npy
pretrained_model_path: models/tenpercent_resnet18.ckpt

biomarker: 2

pruning: 4
batch_size: 16
lr: 0.0001
epochs: 100

experiment_name: 'cpath-transfer-learning'
run_name: 'lr:0.0001_batch:16_pruning:4_reinitialized'
